name: Continuous Delivery
on:
  push:
    branches:
      - main  # Ou o branch que você deseja monitorar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # continuous delivery: creating a zip
      - name: Upload an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado
          path: |
            '**.py'
            README.md

      # continuous deployment
      - uses: Shopify/upload-to-release@master
        with:
          name: projetozipado
          path: projetozipado.zip
          repo-token: ${{ secrets.GITHUB_TOKEN }}
